### ISSUE TITLE
[Feature Request] Add GraphQL API documentation

### ISSUE THREAD

**Issue by matoszz** [theopenlane/core#287]
Similar to how tools create swagger / open api documentation sites, there are lesser-known but still highly valuable methods of performing a similar documentation setup for graphQL; [spectaql](https://github.com/anvilco/spectaql) is one but I'm certain there are others - would be great to incorporate both OpenAPI docs + GraphQL docs ! <3

**Comment by golanglemonade** [comment]
We now generate graphql docs using the `docusaurus-graphql-plugin` and include the apollo explorer documentation: https://docs.theopenlane.io/docs/api/graph-api/queries
